# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protocol', models.CharField(max_length=250)),
                ('ListenAddress', models.CharField(max_length=250)),
                ('ListenPort', models.CharField(max_length=250)),
                ('RemoteAddress', models.CharField(max_length=250)),
                ('RemotePort', models.CharField(max_length=250)),
                ('Status', models.CharField(max_length=250)),
                ('Time', models.CharField(max_length=250)),
                ('Date', models.CharField(max_length=250)),
            ],
        ),
    ]
