# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Date',
            field=models.DateField(max_length=250),
        ),
    ]
