# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_auto_20170326_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protocol', models.CharField(max_length=250)),
                ('ListenAddress', models.CharField(max_length=250)),
                ('ListenPort', models.CharField(max_length=250)),
                ('RemoteAddress', models.CharField(max_length=250)),
                ('RemotePort', models.CharField(max_length=250)),
                ('Status', models.CharField(max_length=250)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
